title: Nemanja
email: nemanjan00@gmail.com
description: >-
  Just a place where I write when I have something geeky to say.
baseurl: ""
url: "https://nemanja.top"
github_username: nemanjan00
permalink: /:categories/:year/:month/:day/:title

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
